language: node_js

before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.19.1-1

cash:
  yarn: true

install:
 - yarn
 - yarn global add solhint
 - yarn global add codecov 
 
# notifications:
  # email: true
  # slack: akropolisio:q9lFKpyTHVdsNQ8JD3sA6VQP

node_js:
  - 12

script: 
  yarn lint && yarn coverage
  - codecov

# after_success:
  # - cat coverage/lcov.info | npx coveralls